### ISSUE TITLE
Table editor for JSON values

### ISSUE THREAD

**Issue by csytsma** [JOSM/geojson#25] opened 2018-10-29 23:29 UTC
This is an enhancement request.  It would be a great if there was a way to edit the keys:values in the JSON file in a table view.  Very similar to https://josm.openstreetmap.de/attachment/ticket/5038/josm%20table%20edit.png

I would use it for adding and changing key:values quickly, instead of having to click on each element on the map to update them.

Sort the table by clicking on a column header, then quickly go through and make the edits.

I'd be willing to help, it's just been awhile since I've done any java programming, and wouldn't be able to do it on my own.

**Comment by don-vip** [comment] 2019-10-05 18:28
GeoJson now creates standard OSM data layers and is considered to be included in core (https://josm.openstreetmap.de/ticket/10564). So this ticket is now a duplicate of https://josm.openstreetmap.de/ticket/5038

**Closed by don-vip** 2019-10-05 18:28 UTC
